[build]
command = "hugo mod get -u && hugo mod npm pack && npm install && hugo --gc --minify"
publish = "public"

[context.production.environment]
GO_VERSION = "1.21.3"
HUGO_VERSION = "0.115.4"
NODE_VERSION = "v20.5.0"
NPM_VERSION  = "9.8.0"

[context.deploy-preview.environment]
GO_VERSION = "1.21.3"
HUGO_VERSION = "0.115.4"
NODE_VERSION = "v20.5.0"
NPM_VERSION  = "9.8.0"
