[build]
command = "hugo mod vendor && npm ci && npm run import:r2 && npm run build"
publish = "public"

[build.environment]
GO_VERSION = "1.26.0"
HUGO_VERSION = "0.152.2"

[dev]
command = "npm run dev"
framework = "hugo"
